### ISSUE TITLE
Error launching the module

### ISSUE THREAD

**Issue by claudio-mazzuco** [vivekmore/generator-jhipster-nav-element#34]
Launching yo jhipster-nav-element from directory project, after inserting the page name i obtain this error:

processing for  en prefix [en]
processing for  it prefix

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

events.js:187
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'charAt' of undefined
    at rewrite (C:\Users\Claudio\AppData\Roaming\npm\node_modules\generator-jhipster-nav-element\node_modules\generator-jhipster\generators\utils.js:121:38)
    at Object.rewriteFile (C:\Users\Claudio\AppData\Roaming\npm\node_modules\generator-jhipster-nav-element\node_modules\generator-jhipster\generators\utils.js:65:18)
    at Object.write (C:\Users\Claudio\AppData\Roaming\npm\node_modules\generator-jhipster-nav-element\generators\app\about-us\about-us-ng-template-writer.js:153:19)
    at writeDefaultTemplate (C:\Users\Claudio\AppData\Roaming\npm\node_modules\generator-jhipster-nav-element\generators\app\main-writer.js:28:34)
    at Object.writeTemplate (C:\Users\Claudio\AppData\Roaming\npm\node_modules\generator-jhipster-nav-element\generators\app\main-writer.js:13:9)
    at module.exports.writeTemplateSpecificFiles (C:\Users\Claudio\AppData\Roaming\npm\node_modules\generator-jhipster-nav-element\generators\app\index.js:48:28)
    at Object.<anonymous> (C:\Users\Claudio\AppData\Roaming\npm\node_modules\generator-jhipster-nav-element\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:424:27)
    at C:\Users\Claudio\AppData\Roaming\npm\node_modules\generator-jhipster-nav-element\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\Claudio\AppData\Roaming\npm\node_modules\generator-jhipster-nav-element\node_modules\run-async\index.js:24:19
Emitted 'error' event on Generator instance at:
    at Immediate.<anonymous> (C:\Users\Claudio\AppData\Roaming\npm\node_modules\generator-jhipster-nav-element\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:433:22)

jhipster version 6.5.1

**Comment by claudio-mazzuco** [comment]
this is how i use it

This generator can also be run with: yo jhipster-nav-element



        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v6.5.1
Application files will be generated in folder: c:\Sviluppo\Generali\axway\axway-rules
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________


Welcome to the JHipster Navigation Element generator! v2.2.0

? What would you like to generate? (More components will be added soon! Stay tuned...) A Simple Page (with a corresponding nav element)
? What would you like the navigation element id to be? (e.g. aboutUs, about_us) categories
------------------------------------------------------------

**Comment by vivekmore** [comment]
- Please follow the issue template below for bug reports.
- For bug reports it is mandatory to run the command `jhipster info` in your project's root folder, and paste the result here.
- Tickets opened without any of these pieces of information will be **closed** without any explanation.

##### **Overview of the issue**



##### **Motivation for or Use Case**



##### **Reproduce the error**



##### **Related issues**



##### **Suggest a Fix**



##### **JHipster Version(s)**



##### **generator-jhipster-nav-element Version(s)**



##### **JHipster configuration**



##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**



##### **Browsers and Operating System**



-   [ ] Checking this box is mandatory (this is just to show you read everything)
